// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("other")>]
[<assembly: AssemblyProductAttribute("Ficus")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2018-03-04T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: InternalsVisibleToAttribute("Ficus.Tests")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","4cb508c83bc0d7ae7340c41b0c439f4a58a39a4e")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "other"
    let [<Literal>] AssemblyProduct = "Ficus"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2018-03-04T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] InternalsVisibleTo = "Ficus.Tests"
    let [<Literal>] AssemblyInformationalVersion = "0.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "4cb508c83bc0d7ae7340c41b0c439f4a58a39a4e"
